/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sookie.trc.common;

/**
 *
 * @author jiayu.li
 */
public class Library {
    /**
     * test
     * @return test boolean
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
